create table if not exists public.support_signups (
	id bigint generated by default as identity primary key,
	created_at timestamptz not null default now(),
	phone text,
	email text,
	privacy_consent boolean not null default true,
	consent_version text not null,
	cta_position text,
	constraint support_signups_contact_required check (
		email is not null or phone is not null
	),
	constraint support_signups_email_format check (
		email is null or email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
	),
	constraint support_signups_phone_format check (
		phone is null or phone ~ '^\+?[0-9]{8,15}$'
	),
	constraint support_signups_cta_position_check check (
		cta_position is null or cta_position in ('hero', 'bottom')
	)
);

create index if not exists support_signups_created_at_idx
	on public.support_signups (created_at desc);

alter table public.support_signups enable row level security;

drop policy if exists "Public can create support signups" on public.support_signups;
create policy "Public can create support signups"
	on public.support_signups
	for insert
	to anon, authenticated
	with check (
		privacy_consent is true
		and (email is not null or phone is not null)
	);

drop policy if exists "Authenticated users can read support signups" on public.support_signups;
drop policy if exists "Admins can read support signups" on public.support_signups;

drop function if exists public.is_admin();
drop table if exists public.admin_users;

grant usage on schema public to anon, authenticated;
grant insert on public.support_signups to anon, authenticated;
grant usage, select on sequence public.support_signups_id_seq to anon, authenticated;
